### 1. Import the numpy package under the name np (★☆☆)

In [2]:
import numpy as np


### 2. Print the numpy version and the configuration (★☆☆)

In [6]:
numpy.__version__

'1.23.2'

### 3. Create a null vector of size 10 (★☆☆)

In [10]:
x=np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

### 4. How to find the memory size of any array (★☆☆)

In [18]:
memory_size=x.itemsize*x.size
memory_size

80

### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [19]:
numpy.add?

### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [21]:
x=np.zeros(10)
x[4]=1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [23]:
x=np.random.randint(10,49,(1,10))
x

array([[11, 44, 11, 21, 19, 39, 21, 20, 24, 28]])

### 8. Reverse a vector (first element becomes last) (★☆☆)

In [64]:
x=np.random.randint(10,49,(1,10))
print(x)


[[36 12 44 23 48 10 35 17 12 32]]


In [65]:
np.flip(x,1)

array([[32, 12, 17, 35, 10, 48, 23, 44, 12, 36]])

In [68]:
print(x[::,::-1])

[[32 12 17 35 10 48 23 44 12 36]]


9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [29]:
x=np.random.randint(0,8,(3,3))
x

array([[3, 1, 6],
       [6, 0, 1],
       [7, 2, 4]])

10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [39]:
x= [1,2,0,0,4,0]
x= np.array(x)
result=np.where (x==0)
print(result[0],sep='\n')

[2 3 5]


11. Create a 3x3 identity matrix (★☆☆)


In [41]:
x=np.identity(3)
x

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

12. Create a 3x3x3 array with random values (★☆☆)

In [43]:
x=np.random.randint(1,99,(3,3,3))
x

array([[[32, 37, 51],
        [30,  2, 28],
        [28, 19, 89]],

       [[49, 40, 94],
        [87, 83, 66],
        [45, 31, 81]],

       [[85, 90, 82],
        [18, 96, 95],
        [40, 32, 97]]])

13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [48]:
x=np.random.randint(1,99,(10,10))
print(x)
min_value=x.min(axis=None)
max_value=x.max(axis=None)
min_value,max_value

[[84  3 50 18 47 31 62 97 22 60]
 [23 30  7 67 96 54 78 42 13  5]
 [36 33 71  6 74 24 80 67 46  9]
 [97 97 17 25 37 96 27 86 93 82]
 [29  3 59 97 16 85 29 65 73  3]
 [95 10 56 36 35 66 93 14 16 67]
 [57 94 64 33 73 89 32 44 21 17]
 [85 49 39 82 59  6 46 94 72 63]
 [21 59 39 42 56 63 57 38 15 87]
 [15 15 97 33 26 51 26 96  9 32]]


(3, 97)

14. Create a random vector of size 30 and find the mean value (★☆☆)

In [62]:
x=np.random.randint(0,99,(1,30))
print(x)
mean_value=x.mean(axis=None)
print("mean value is %.2f" %mean_value)

[[76 21  1 19 53 51 69 12 40 12 53  2 58 88  8 94  1 60  7 34 25 15 12 40
  39 29 48  4 12 78]]
mean value is 35.37


15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [63]:
x = np.ones((5,5))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)


Original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [84]:
x=np.ones((3,3))
print(x)
new_x=np.pad(x, pad_width=1,
               constant_values=0)
print("after padding : \n",new_x)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
after padding : 
 [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


17. What is the result of the following expression? (★☆☆)

a)0 * np.nan

b)np.nan == np.nan

c)np.inf > np.nan

d)np.nan - np.nan

e)np.nan in set([np.nan])

f)0.3 == 3 * 0.1

In [85]:
0 * np.nan

nan

In [86]:
np.nan == np.nan

False

In [87]:
np.inf > np.nan

False

In [88]:
np.nan - np.nan

nan

In [89]:
np.nan in set([np.nan])

True

In [90]:
0.3 == 3 * 0.1

False

18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [91]:
np.diag?

In [95]:
1+np.arange(4)

array([1, 2, 3, 4])

In [96]:
x=np.diag(1+np.arange(4),k=-1)
x

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [102]:
Z = np.zeros ((8,8))
Z[1::2, ::2]= 1  #first argument slice the rows and second argument slice the columns
Z[::2, 1::2] = 1
Z

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [103]:
Z[1::2]

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [104]:
Z[::2]

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

In [117]:
x=np.random.randint(1,9,(1,10))
x,x.ndim #2 dimensional array
#referring problem no  8

(array([[2, 6, 4, 8, 4, 7, 4, 5, 4, 7]]), 2)

In [119]:
y=[1,2,3,4]
y=np.array(y)#list to numpy array
y,y.ndim

(array([1, 2, 3, 4]), 1)

## 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [126]:

print (np.unravel_index(100, (6,7,8)))

(1, 5, 4)


In [124]:
np.unravel_index?

21. Create a checkerboard 8x8 matrix using the tile function

In [128]:
array= np.array([[0,1], [1,0]])
Z = np.tile(array,(4,4))
print (Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [129]:
np.tile?

22. Normalize a 5x5 random matrix (★☆☆)

In [145]:
x=np.random.randint(1,9,(5,5))
print(x)
normalized=np.linalg.norm(x)
print(x/normalized)

[[4 2 5 4 4]
 [7 1 5 3 2]
 [6 2 2 3 4]
 [8 7 8 3 8]
 [5 7 2 4 6]]
[[0.16142686 0.08071343 0.20178358 0.16142686 0.16142686]
 [0.28249701 0.04035672 0.20178358 0.12107015 0.08071343]
 [0.24214029 0.08071343 0.08071343 0.12107015 0.16142686]
 [0.32285372 0.28249701 0.32285372 0.12107015 0.32285372]
 [0.20178358 0.28249701 0.08071343 0.16142686 0.24214029]]


## 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [152]:
x=np.random.randint(1,9,(5,3))
y=np.random.randint(1,9,(3,2))
print("first array \n" ,x,"\n next array\n ",y)

first array 
 [[1 3 5]
 [4 5 7]
 [2 1 6]
 [7 1 5]
 [7 1 2]] 
 next array
  [[5 6]
 [6 3]
 [2 8]]


In [153]:

res=np.dot(x,y)
res

array([[33, 55],
       [64, 95],
       [28, 63],
       [51, 85],
       [45, 61]])

25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [158]:
arr=np.arange(1,16)
print(arr)
arr[(arr>=3) & (arr<=8)]*=(-1)
arr

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


array([ 1,  2, -3, -4, -5, -6, -7, -8,  9, 10, 11, 12, 13, 14, 15])

26. What is the output of the following script? (★☆☆)
#Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

In [1]:
print(sum(range(5),-1)) 
from numpy import * 
print(sum(range(5),-1))

9
10


27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

Z**Z

2 << Z >> 2

Z <- Z

1j*Z

Z/1/1

Z < Z > Z

In [6]:
z=np.arange(10)
z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
z**z

array([        1,         1,         4,        27,       256,      3125,
           46656,    823543,  16777216, 387420489])

In [7]:
2 << z >> 2

array([  0,   1,   2,   4,   8,  16,  32,  64, 128, 256], dtype=int32)

In [8]:
z<-z

array([False, False, False, False, False, False, False, False, False,
       False])

In [9]:
1j*z

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j, 0.+5.j, 0.+6.j, 0.+7.j,
       0.+8.j, 0.+9.j])

In [10]:
z/1/1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [12]:
z<z>Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

28. What are the result of the following expressions? (★☆☆)

np.array(0) / np.array(0)

np.array(0) // np.array(0)

np.array([np.nan]).astype(int).astype(float)
 

In [13]:
np.array(0) / np.array(0)

C:\temp\ipykernel_18028\873513115.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


nan

In [14]:
np.array(0) // np.array(0)

C:\temp\ipykernel_18028\2018018105.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


0

In [20]:
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

29. How to round away from zero a float array ? (★☆☆)

In [25]:
arr = np.random.random((5,5))
print(arr)
arr = np.round(arr,2)
print(arr) 

[[0.55111125 0.00612868 0.42662941 0.85971985 0.45901557]
 [0.81689165 0.891704   0.66798851 0.08187432 0.56104179]
 [0.26225788 0.26282057 0.36832108 0.42141492 0.35812699]
 [0.76102609 0.86725628 0.06832799 0.28514258 0.92417229]
 [0.14897997 0.78701641 0.15952168 0.77616886 0.33288808]]
[[0.55 0.01 0.43 0.86 0.46]
 [0.82 0.89 0.67 0.08 0.56]
 [0.26 0.26 0.37 0.42 0.36]
 [0.76 0.87 0.07 0.29 0.92]
 [0.15 0.79 0.16 0.78 0.33]]


30. How to find common values between two arrays? (★☆☆)

In [30]:
arr_1=np.array([4,8,5,6,9,7,5])
arr_2=np.array([58,9,5,5,6,4,6])
print(np.intersect1d(arr_1, arr_2))

[4 5 6 9]


31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [36]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# An equivalent way, with a context manager:

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

32. Is the following expressions true? (★☆☆)
np.sqrt(-1) == np.emath.sqrt(-1)

In [39]:
 np.sqrt(-1) == np.emath.sqrt(-1)

False

In [43]:
 np.sqrt(-1) 

nan

In [41]:
np.emath.sqrt(-1)

1j

33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [45]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print(yesterday,today,tomorrow)

2022-08-26 2022-08-27 2022-08-28


34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [47]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [48]:
A=np.ones(3)*1
B=np.ones(3)*2
C=np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.dot(A,B)

-4.5

36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [54]:
Z = np.random.uniform(0,10.5,10)
print(Z)
print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))

[10.36305707  1.99909547  6.29944674  1.57245523  9.07437668  3.45499669
  5.50662343  1.70778628  6.83544883  8.68286509]
[10.  1.  6.  1.  9.  3.  5.  1.  6.  8.]
[10.  1.  6.  1.  9.  3.  5.  1.  6.  8.]
[10.  1.  6.  1.  9.  3.  5.  1.  6.  8.]
[10  1  6  1  9  3  5  1  6  8]


37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [3]:
x=np.random.randint(0,4,(5,5))
x

array([[2, 2, 0, 0, 2],
       [1, 3, 3, 2, 1],
       [1, 2, 2, 3, 3],
       [1, 0, 1, 1, 3],
       [0, 0, 0, 0, 0]])

38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [6]:
rng = np.random.default_rng()
arr=rng.integers(10, size=(10))
arr

array([3, 3, 6, 5, 8, 0, 7, 0, 7, 1], dtype=int64)

39. Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [8]:
x=np.random.random((10))
x

array([0.24336198, 0.58226199, 0.93347596, 0.87758546, 0.22911708,
       0.76033515, 0.59079262, 0.99573955, 0.25444557, 0.50643486])

40. Create a random vector of size 10 and sort it (★★☆)

In [13]:
x=np.random.randint(1,9,(10))
np.sort(x)

array([2, 2, 3, 4, 5, 5, 6, 6, 7, 7])

41. How to sum a small array faster than np.sum? (★★☆)

In [16]:
Z = np.arange(1000000)

np.add.reduce(Z)

1783293664

42. Consider two random array A and B, check if they are equal (★★☆)

In [20]:
A=np.array([4,5,7,8,8])
B=np.array([4,5,7,8,8])
equal = np.allclose(A,B)

print(equal)

True


43. Make an array immutable (read-only) (★★☆)

In [3]:
a = np.arange(10)
a.flags.writeable = False

In [4]:
a[0]=1
#gives error as it becomes immutable

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)


In [6]:
Z=np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
X,Y

(array([0.81769916, 0.05721957, 0.1738187 , 0.42738556, 0.65198243,
        0.22214625, 0.75754339, 0.83149556, 0.93313148, 0.827433  ]),
 array([0.45197643, 0.29390579, 0.06265173, 0.40386859, 0.96625219,
        0.84367528, 0.95524626, 0.90002942, 0.20717596, 0.04788432]))

In [7]:
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
R,T

(array([0.93429899, 0.29942394, 0.1847652 , 0.58802062, 1.16564334,
        0.87243162, 1.21916668, 1.22533172, 0.95585367, 0.8288174 ]),
 array([0.50494573, 1.37851481, 0.34594766, 0.75711476, 0.97721575,
        1.31333246, 0.900317  , 0.82495757, 0.21847838, 0.05780646]))

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)


In [9]:
A=np.random.randint(1,9,(10))
A[A.argmax()]=0
A

array([1, 5, 1, 7, 7, 3, 0, 8, 3, 5])

In [10]:
A.argmax()

7

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [14]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z

array([[(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)],
       [(0., 0.), (0., 0.), (0., 0.), (0., 0.), (0., 0.)]],
      dtype=[('x', '<f8'), ('y', '<f8')])

In [15]:
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
Z

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [24]:
X = np.arange(8)
Y = X + 0.5
X,Y

(array([0, 1, 2, 3, 4, 5, 6, 7]),
 array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5]))

In [25]:
c=np.subtract.outer(X,Y)
c

array([[-0.5, -1.5, -2.5, -3.5, -4.5, -5.5, -6.5, -7.5],
       [ 0.5, -0.5, -1.5, -2.5, -3.5, -4.5, -5.5, -6.5],
       [ 1.5,  0.5, -0.5, -1.5, -2.5, -3.5, -4.5, -5.5],
       [ 2.5,  1.5,  0.5, -0.5, -1.5, -2.5, -3.5, -4.5],
       [ 3.5,  2.5,  1.5,  0.5, -0.5, -1.5, -2.5, -3.5],
       [ 4.5,  3.5,  2.5,  1.5,  0.5, -0.5, -1.5, -2.5],
       [ 5.5,  4.5,  3.5,  2.5,  1.5,  0.5, -0.5, -1.5],
       [ 6.5,  5.5,  4.5,  3.5,  2.5,  1.5,  0.5, -0.5]])

In [26]:
c=1.0/c
c

array([[-2.        , -0.66666667, -0.4       , -0.28571429, -0.22222222,
        -0.18181818, -0.15384615, -0.13333333],
       [ 2.        , -2.        , -0.66666667, -0.4       , -0.28571429,
        -0.22222222, -0.18181818, -0.15384615],
       [ 0.66666667,  2.        , -2.        , -0.66666667, -0.4       ,
        -0.28571429, -0.22222222, -0.18181818],
       [ 0.4       ,  0.66666667,  2.        , -2.        , -0.66666667,
        -0.4       , -0.28571429, -0.22222222],
       [ 0.28571429,  0.4       ,  0.66666667,  2.        , -2.        ,
        -0.66666667, -0.4       , -0.28571429],
       [ 0.22222222,  0.28571429,  0.4       ,  0.66666667,  2.        ,
        -2.        , -0.66666667, -0.4       ],
       [ 0.18181818,  0.22222222,  0.28571429,  0.4       ,  0.66666667,
         2.        , -2.        , -0.66666667],
       [ 0.15384615,  0.18181818,  0.22222222,  0.28571429,  0.4       ,
         0.66666667,  2.        , -2.        ]])

In [27]:
print(np.linalg.det(c))


3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)


In [29]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [33]:
z=np.arange(8)
print(z)

[0 1 2 3 4 5 6 7]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)


In [52]:
a=np.arange(8)
b=np.random.uniform(0,8)
a,b

(array([0, 1, 2, 3, 4, 5, 6, 7]), 6.385457997950157)

In [53]:
index = (np.abs(a-b)).argmin()
print(a[index])

6



#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [54]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


C:\temp\ipykernel_15176\274409719.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)


In [56]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
X,Y

(array([[0.4824258 , 0.65305302, 0.89191249, 0.02365033, 0.15543399,
         0.7881327 , 0.17932789, 0.87764754, 0.10110757, 0.79453537]]),
 array([[0.09744633, 0.61633499, 0.66025062, 0.50773741, 0.21009215,
         0.69804588, 0.52271862, 0.40258961, 0.54975315, 0.28068326]]))

In [58]:
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.54622256 0.69600863 0.61547844 0.34585072 0.6739262
  0.52223066 0.49931217 0.59159534 0.36192286]
 [0.54622256 0.         0.24286298 0.63870274 0.64238458 0.1578708
  0.48288665 0.31004803 0.55594687 0.36425175]
 [0.69600863 0.24286298 0.         0.88155514 0.86315886 0.11044784
  0.72573539 0.25805558 0.79848739 0.39185926]
 [0.61547844 0.63870274 0.88155514 0.         0.32551442 0.78781382
  0.15639674 0.86044599 0.08811894 0.80362761]
 [0.34585072 0.64238458 0.86315886 0.32551442 0.         0.79900344
  0.31353824 0.74742737 0.34397814 0.64298808]
 [0.6739262  0.1578708  0.11044784 0.78781382 0.79900344 0.
  0.6335479  0.30871882 0.70284726 0.41741172]
 [0.52223066 0.48288665 0.72573539 0.15639674 0.31353824 0.6335479
  0.         0.70857696 0.0827604  0.66110616]
 [0.49931217 0.31004803 0.25805558 0.86044599 0.74742737 0.30871882
  0.70857696 0.         0.79036158 0.14754251]
 [0.59159534 0.55594687 0.79848739 0.08811894 0.34397814 0.70284726
  0.0827604  0.79036158

In [59]:
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

C:\Anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"


[[0.         0.62130505 0.53729539 0.83673984 0.69321275 0.85685663
  0.64713438 0.58290434 0.37156459 0.68429465]
 [0.62130505 0.         0.14782011 0.83986545 0.39127559 0.69956614
  0.14429379 0.14012831 0.83076977 0.39122512]
 [0.53729539 0.14782011 0.         0.7011931  0.2802264  0.57806883
  0.27731319 0.24595946 0.69943829 0.27731947]
 [0.83673984 0.83986545 0.7011931  0.         0.47320534 0.21976474
  0.97797987 0.94531126 0.61664122 0.46884741]
 [0.69321275 0.39127559 0.2802264  0.47320534 0.         0.30908761
  0.53541508 0.51817139 0.70906653 0.00994981]
 [0.85685663 0.69956614 0.57806883 0.21976474 0.30908761 0.
  0.84330308 0.82222453 0.72757215 0.30846883]
 [0.64713438 0.14429379 0.27731319 0.97797987 0.53541508 0.84330308
  0.         0.06423005 0.9084814  0.53518553]
 [0.58290434 0.14012831 0.24595946 0.94531126 0.51817139 0.82222453
  0.06423005 0.         0.84835256 0.51677918]
 [0.37156459 0.83076977 0.69943829 0.61664122 0.70906653 0.72757215
  0.9084814  0.84835

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [63]:
Z = (np.random.rand(10)*100).astype(np.float32)
Z

array([38.53426 , 40.8957  , 37.72999 , 36.580772, 19.805923, 61.07688 ,
       48.40021 , 32.54716 , 76.12231 , 59.69217 ], dtype=float32)

In [66]:
Y = Z.view(np.int32)
Y[:]=Z
Y

array([38, 40, 37, 36, 19, 61, 48, 32, 76, 59])

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [69]:
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


C:\temp\ipykernel_15176\2000409876.py:8: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  Z = np.genfromtxt(s, delimiter=",", dtype=np.int)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [70]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [71]:
np.ndenumerate?

In [72]:
np.ndindex?

## 56. Generate a generic 2D Gaussian-like array (★★☆)


In [73]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [74]:
np.meshgrid?

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [77]:
n=10
p=3
Z=np.zeros((n,n))
np.put(Z,np.random.choice(range(n*n),p,replace = False),1)
print(Z)

[[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [84]:
x=np.random.randint(5,10,(5,10))
y=x-x.mean(axis=1).reshape(-1,1)
y

array([[ 0.6,  1.6, -1.4, -2.4,  1.6, -1.4,  0.6,  0.6,  1.6, -1.4],
       [-1.3,  1.7,  0.7, -0.3,  0.7, -1.3, -1.3,  0.7,  1.7, -1.3],
       [ 1.6,  0.6, -2.4, -0.4,  0.6,  0.6,  0.6, -1.4,  1.6, -1.4],
       [-1.4, -0.4, -1.4,  0.6, -1.4, -0.4, -0.4,  1.6,  1.6,  1.6],
       [-1.5, -1.5, -0.5, -0.5, -1.5,  2.5,  1.5,  2.5, -0.5, -0.5]])

#### 59. How to sort an array by the nth column? (★★☆)

In [88]:
z=np.random.randint(1,10,(10,10))
print(z)

[[3 1 7 5 3 5 5 5 1 5]
 [3 4 8 1 6 5 4 2 9 2]
 [7 9 7 4 2 9 5 5 8 8]
 [7 6 5 1 4 4 9 8 1 1]
 [2 7 3 5 7 1 7 2 6 2]
 [6 5 7 4 4 4 7 5 9 1]
 [6 4 2 1 9 5 1 3 1 2]
 [7 6 5 5 3 9 9 3 8 9]
 [8 6 9 6 4 3 4 5 8 4]
 [9 7 4 8 9 2 4 3 7 8]]


In [90]:
z_sort=z[z[:,1].argsort()]
print(z_sort) #sort the elements by column 1

array([[3, 1, 7, 5, 3, 5, 5, 5, 1, 5],
       [3, 4, 8, 1, 6, 5, 4, 2, 9, 2],
       [6, 4, 2, 1, 9, 5, 1, 3, 1, 2],
       [6, 5, 7, 4, 4, 4, 7, 5, 9, 1],
       [7, 6, 5, 1, 4, 4, 9, 8, 1, 1],
       [7, 6, 5, 5, 3, 9, 9, 3, 8, 9],
       [8, 6, 9, 6, 4, 3, 4, 5, 8, 4],
       [2, 7, 3, 5, 7, 1, 7, 2, 6, 2],
       [9, 7, 4, 8, 9, 2, 4, 3, 7, 8],
       [7, 9, 7, 4, 2, 9, 5, 5, 8, 8]])

#### 60. How to tell if a given 2D array has null columns? (★★☆)


In [91]:
z=np.random.randint(0,3,(5,5))
print((~z.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [101]:
z=np.random.uniform(0,1,10)
val=0.5
z

array([0.83804025, 0.10853198, 0.8732595 , 0.97243485, 0.03513007,
       0.73568282, 0.66518128, 0.24910174, 0.39710304, 0.27775082])

In [102]:
(z-val)

array([ 0.33804025, -0.39146802,  0.3732595 ,  0.47243485, -0.46486993,
        0.23568282,  0.16518128, -0.25089826, -0.10289696, -0.22224918])

In [103]:
np.abs(z-val)

array([0.33804025, 0.39146802, 0.3732595 , 0.47243485, 0.46486993,
       0.23568282, 0.16518128, 0.25089826, 0.10289696, 0.22224918])

In [104]:
np.abs(z-val).argmin()

8

In [106]:
z[8]

0.3971030443230744

In [107]:
z.flat[8]

0.3971030443230744

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [117]:
x=np.random.randint(1,10,(1,3))
y=np.random.randint(1,10,(3,1))
sum_xy=np.nditer([x,y,None])

In [118]:
x,y

(array([[8, 6, 6]]),
 array([[8],
        [9],
        [4]]))

In [119]:
for x,y,z in sum_xy : z[...]=x+y

In [120]:
sum_xy.operands[2]

array([[16, 14, 14],
       [17, 15, 15],
       [12, 10, 10]])

#### 63. Create an array class that has a name attribute (★★☆)

In [122]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [126]:
z=np.ones(10)
i=np.random.randint(0,len(z),20)
z,i

(array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([0, 3, 2, 0, 0, 2, 3, 4, 4, 6, 7, 9, 9, 2, 1, 6, 9, 5, 3, 3]))

In [127]:
z+=np.bincount(i,minlength=len(z))
print(z)

[4. 2. 4. 5. 3. 2. 3. 2. 1. 4.]


In [128]:
np.add.at(z,i, 1)
print(z)

[7. 3. 7. 9. 5. 3. 5. 3. 1. 7.]


In [130]:
np.bincount?

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [129]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [131]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


In [132]:
#method 2
w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)

# View each pixel as a single 24-bit integer, rather than three 8-bit bytes
I24 = np.dot(I.astype(np.uint32),[1,256,65536])

# Count unique colours
n = len(np.unique(I24))
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [135]:
A = np.random.randint(0,10,(3,4,3,4))
print(A)
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)

[[[[9 5 3 0]
   [7 1 9 8]
   [8 1 1 4]]

  [[4 6 4 2]
   [6 8 0 3]
   [7 7 0 4]]

  [[0 9 4 5]
   [4 8 3 2]
   [1 0 7 3]]

  [[2 4 9 6]
   [1 6 3 4]
   [9 5 9 5]]]


 [[[9 7 6 8]
   [1 0 8 3]
   [1 2 9 8]]

  [[7 3 4 8]
   [1 3 9 2]
   [0 4 7 5]]

  [[2 8 9 0]
   [5 5 3 5]
   [2 8 6 8]]

  [[7 3 0 3]
   [7 1 1 8]
   [0 7 8 9]]]


 [[[2 8 9 2]
   [7 2 3 2]
   [6 4 2 8]]

  [[0 4 3 0]
   [8 7 0 1]
   [9 7 3 1]]

  [[6 7 2 9]
   [6 8 4 7]
   [4 6 8 6]]

  [[6 9 7 6]
   [7 4 3 1]
   [5 4 7 4]]]]
[[56 51 46 63]
 [62 53 61 54]
 [55 43 73 63]]


In [136]:
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[56 51 46 63]
 [62 53 61 54]
 [55 43 73 63]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [138]:

# Author: Jaime Fernández del Río

D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.25079244 0.58522239 0.47164563 0.51996417 0.57792493 0.44067601
 0.42565061 0.47722306 0.36106948 0.66430086]


In [139]:
# Pandas solution as a reference due to more intuitive code

import pandas as pd
print(pd.Series(D).groupby(S).mean())


0    0.250792
1    0.585222
2    0.471646
3    0.519964
4    0.577925
5    0.440676
6    0.425651
7    0.477223
8    0.361069
9    0.664301
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★)

In [140]:

# Author: Mathieu Blondel

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)


array([0.72206215, 1.47508012, 1.68417892, 2.10976812, 1.87499726])

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [141]:

# Author: Warren Weckesser

Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)


[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [142]:

A = np.ones((5,5,3))
print(A)
B = 2*np.ones((5,5))
print(B)
print(A * B[:,:,None])


[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]
[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [143]:

# Author: Eelco Hoogendoorn

A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)


[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [144]:

# Author: Nicolas P. Rougier

faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)


[( 0, 32) ( 0, 67) ( 4, 29) ( 4, 52) ( 6, 45) ( 6, 88) ( 9, 22) ( 9, 39)
 (22, 39) (26, 29) (26, 38) (29, 38) (29, 52) (31, 65) (31, 93) (32, 67)
 (38, 55) (38, 59) (45, 53) (45, 77) (45, 88) (53, 77) (55, 59) (55, 66)
 (55, 74) (65, 93) (66, 74) (67, 74) (67, 90) (74, 90)]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [145]:

# Author: Jaime Fernández del Río

C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)


[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [147]:
# Author: Jaime Fernández del Río

def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [148]:
# Author: Jeff Luo (@Jeff1999)
# make sure your NumPy >= 1.20.0

from numpy.lib.stride_tricks import sliding_window_view

Z = np.arange(20)
print(sliding_window_view(Z, window_shape=3).mean(axis=-1))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [150]:
# Author: Joe Kington / Erik Rigtorp
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


In [151]:
# Author: Jeff Luo (@Jeff1999)

Z = np.arange(10)
print(sliding_window_view(Z, window_shape=3))

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [152]:

# Author: Nathaniel J. Smith

Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)


array([-0.4045668 ,  0.42305713, -0.90183358, -0.76647999,  0.35102673,
       -0.41096389, -0.52071037, -0.14699471, -0.77634707, -0.58236521,
        0.64721503,  0.91047599, -0.25843193,  0.04537568,  0.96757146,
        0.71412216, -0.60906114,  0.18368376,  0.70614894,  0.24735292,
        0.08407364,  0.19871479,  0.20602131, -0.44457831,  0.10285872,
        0.62735614, -0.23503388,  0.80931926,  0.18219551,  0.54596508,
       -0.61848963, -0.94963679, -0.4812159 ,  0.51482445,  0.09887771,
       -0.73677044, -0.02342571,  0.82061718,  0.94763858, -0.33269784,
        0.73423228,  0.3670926 , -0.30757314, -0.65002128, -0.67836722,
        0.21585701,  0.67156273,  0.89921222, -0.6939485 ,  0.16285136,
       -0.71548203, -0.12987691, -0.28734162,  0.38102725,  0.88596725,
       -0.59882193,  0.7944915 , -0.02291361, -0.20347133,  0.86844668,
       -0.85948086,  0.56296837,  0.44477261, -0.84444007, -0.03262493,
        0.09492532,  0.66490218,  0.62804626, -0.24760934, -0.27

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [153]:

def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))


[7.28434735 3.13588618 8.98190688 4.79752923 4.72859467 0.41952374
 5.17504824 3.99713676 4.17631027 3.21597928]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [154]:

# Author: Italmassov Kuanysh

# based on distance function from previous question
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))


[[ 7.9271529   6.8309564  11.9620554   3.37595944  7.9783867   1.11519006
  12.96323016  1.3532205  13.61597101  8.87047048]
 [ 3.3714835   5.78875186  2.86934055  6.88300782 15.07549331  0.56934571
   7.92816499  1.18823353 14.22791149  9.68232483]
 [ 7.89151719 11.54333757  4.64969914  9.77835646  7.43255839 17.43900011
   2.30876702 16.21704977  5.19521205  9.96205557]
 [ 0.88476611  2.11248856  3.01509444  3.63283117 10.51436014  3.23682123
   5.64544641  4.4172339  10.15298509  5.56584224]
 [ 4.66175668  6.81492986  4.53658491  5.68899344  1.63433054 12.54785075
   0.66298357 12.05067477  0.03157055  4.68354669]
 [ 4.26626279  6.1200038   4.44716861  5.22847481 14.02508213  0.81943242
   8.89813702  0.61405859 14.2872815   9.70856639]
 [ 5.93073874  3.14792899 13.28195338  8.06898131  2.33058478  2.76650348
  11.24023299  1.67274694  9.3064369   4.49209739]
 [ 0.40403863  2.57740326  1.11039143  6.35272208 12.82383321  2.64536985
   5.02797733  4.34467684 11.03325353  6.49508316]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [155]:

# Author: Nicolas Rougier

Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)


IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [157]:
# Author: Stefan van der Walt

Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


In [158]:
# Author: Jeff Luo (@Jeff1999)

Z = np.arange(1, 15, dtype=np.uint32)
print(sliding_window_view(Z, window_shape=4))

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [159]:

# Author: Stefan van der Walt

Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


In [160]:
# alternative solution:
# Author: Jeff Luo (@Jeff1999)

rank = np.linalg.matrix_rank(Z)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [161]:

Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())


2


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [162]:
# Author: Chris Barker

Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[2 0 4]
   [2 0 2]
   [1 3 4]]

  [[0 4 4]
   [0 2 1]
   [3 4 3]]

  [[4 4 2]
   [2 1 0]
   [4 3 1]]

  [[4 2 3]
   [1 0 1]
   [3 1 4]]

  [[2 3 2]
   [0 1 4]
   [1 4 1]]

  [[3 2 4]
   [1 4 1]
   [4 1 3]]

  [[2 4 1]
   [4 1 4]
   [1 3 2]]

  [[4 1 0]
   [1 4 0]
   [3 2 0]]]


 [[[2 0 2]
   [1 3 4]
   [2 2 3]]

  [[0 2 1]
   [3 4 3]
   [2 3 3]]

  [[2 1 0]
   [4 3 1]
   [3 3 4]]

  [[1 0 1]
   [3 1 4]
   [3 4 4]]

  [[0 1 4]
   [1 4 1]
   [4 4 4]]

  [[1 4 1]
   [4 1 3]
   [4 4 0]]

  [[4 1 4]
   [1 3 2]
   [4 0 2]]

  [[1 4 0]
   [3 2 0]
   [0 2 1]]]


 [[[1 3 4]
   [2 2 3]
   [4 3 3]]

  [[3 4 3]
   [2 3 3]
   [3 3 4]]

  [[4 3 1]
   [3 3 4]
   [3 4 3]]

  [[3 1 4]
   [3 4 4]
   [4 3 3]]

  [[1 4 1]
   [4 4 4]
   [3 3 3]]

  [[4 1 3]
   [4 4 0]
   [3 3 3]]

  [[1 3 2]
   [4 0 2]
   [3 3 4]]

  [[3 2 0]
   [0 2 1]
   [3 4 0]]]


 [[[2 2 3]
   [4 3 3]
   [3 3 4]]

  [[2 3 3]
   [3 3 4]
   [3 4 1]]

  [[3 3 4]
   [3 4 3]
   [4 1 3]]

  [[3 4 4]
   [4 3 3]
   [1 3 1]]

  [[4 4 4]
   

In [163]:
# Author: Jeff Luo (@Jeff1999)

Z = np.random.randint(0,5,(10,10))
print(sliding_window_view(Z, window_shape=(3, 3)))

[[[[1 3 4]
   [2 2 3]
   [4 1 2]]

  [[3 4 2]
   [2 3 4]
   [1 2 3]]

  [[4 2 0]
   [3 4 4]
   [2 3 1]]

  [[2 0 2]
   [4 4 4]
   [3 1 4]]

  [[0 2 0]
   [4 4 3]
   [1 4 4]]

  [[2 0 0]
   [4 3 1]
   [4 4 1]]

  [[0 0 0]
   [3 1 2]
   [4 1 3]]

  [[0 0 1]
   [1 2 0]
   [1 3 0]]]


 [[[2 2 3]
   [4 1 2]
   [0 0 1]]

  [[2 3 4]
   [1 2 3]
   [0 1 0]]

  [[3 4 4]
   [2 3 1]
   [1 0 3]]

  [[4 4 4]
   [3 1 4]
   [0 3 1]]

  [[4 4 3]
   [1 4 4]
   [3 1 3]]

  [[4 3 1]
   [4 4 1]
   [1 3 0]]

  [[3 1 2]
   [4 1 3]
   [3 0 3]]

  [[1 2 0]
   [1 3 0]
   [0 3 0]]]


 [[[4 1 2]
   [0 0 1]
   [1 4 2]]

  [[1 2 3]
   [0 1 0]
   [4 2 4]]

  [[2 3 1]
   [1 0 3]
   [2 4 1]]

  [[3 1 4]
   [0 3 1]
   [4 1 1]]

  [[1 4 4]
   [3 1 3]
   [1 1 0]]

  [[4 4 1]
   [1 3 0]
   [1 0 0]]

  [[4 1 3]
   [3 0 3]
   [0 0 0]]

  [[1 3 0]
   [0 3 0]
   [0 0 4]]]


 [[[0 0 1]
   [1 4 2]
   [3 4 2]]

  [[0 1 0]
   [4 2 4]
   [4 2 4]]

  [[1 0 3]
   [2 4 1]
   [2 4 2]]

  [[0 3 1]
   [4 1 1]
   [4 2 0]]

  [[3 1 3]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [164]:

# Author: Eric O. Lebigot
# Note: only works for 2d array and value setting using indices

class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)


[[ 0 13  8 12 13]
 [13  9 12  9 10]
 [ 8 12  2 42 15]
 [12  9 42  4 11]
 [13 10 15 11  3]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [165]:

# Author: Stefan van der Walt

p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.


[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [167]:
# Author: Robert Kern

Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [168]:
# alternative solution:
# Author: Sebastian Wallkötter (@FirefoxMetzger)

Z = np.ones((16,16))
k = 4

windows = np.lib.stride_tricks.sliding_window_view(Z, (k, k))
S = windows[::k, ::k, ...].sum(axis=(-2, -1))

# Author: Jeff Luo (@Jeff1999)

Z = np.ones((16, 16))
k = 4
print(sliding_window_view(Z, window_shape=(k, k))[::k, ::k].sum(axis=(-2, -1)))

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [169]:

# Author: Nicolas Rougier

def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)


[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0
  0 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0
  0 1 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★)

In [170]:

Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])


[9995 9996 9997 9998 9999]
[9998 9999 9997 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [171]:

# Author: Stefan Van der Walt

def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))


[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [172]:

Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)


[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [173]:

# Author: Ryan G.

x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)


3.88 s ± 571 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
1.15 s ± 51.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
678 ms ± 8.37 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [174]:

# Author: Gabe Schwartz

A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)


[1 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [176]:
# Author: Robert Kern

Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

[[2 3 1]
 [1 2 0]
 [0 0 4]
 [1 3 0]
 [2 4 2]
 [1 2 0]
 [4 3 3]
 [0 4 2]
 [0 4 3]
 [0 3 4]]
[[2 3 1]
 [1 2 0]
 [0 0 4]
 [1 3 0]
 [2 4 2]
 [1 2 0]
 [4 3 3]
 [0 4 2]
 [0 4 3]
 [0 3 4]]


In [177]:
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[2 3 1]
 [1 2 0]
 [0 0 4]
 [1 3 0]
 [2 4 2]
 [1 2 0]
 [4 3 3]
 [0 4 2]
 [0 4 3]
 [0 3 4]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [179]:
# Author: Warren Weckesser

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


In [180]:
# Author: Daniel T. McDonald

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [182]:
# Author: Jaime Fernández del Río

Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 1 1]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


In [183]:
# Author: Andreas Kouzelis
# NumPy >= 1.13
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 0]
 [0 1 1]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [184]:

# Author: Alex Riley
# Make sure to read: http://ajcr.net/Basic-guide-to-einsum/

A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)


array([[0.79869181, 0.0082726 , 0.77439402, 0.09002101, 0.83427304,
        0.05707006, 0.56797348, 0.31358369, 0.13001514, 0.20644494],
       [0.52160825, 0.00540265, 0.50573989, 0.05879076, 0.54484557,
        0.03727122, 0.37093112, 0.20479468, 0.08491006, 0.1348247 ],
       [0.77760163, 0.00805415, 0.75394543, 0.08764392, 0.8122433 ,
        0.05556308, 0.55297562, 0.30530322, 0.12658198, 0.20099357],
       [0.66848239, 0.00692393, 0.64814582, 0.07534503, 0.69826286,
        0.04776602, 0.47537769, 0.26246065, 0.10881899, 0.17278856],
       [0.64373628, 0.00666762, 0.62415254, 0.07255588, 0.67241433,
        0.04599781, 0.45778   , 0.25274479, 0.10479069, 0.16639221],
       [0.20092394, 0.00208111, 0.19481144, 0.02264625, 0.20987498,
        0.0143569 , 0.14288299, 0.07888709, 0.03270743, 0.05193459],
       [0.68768073, 0.00712278, 0.66676011, 0.07750888, 0.71831648,
        0.04913783, 0.4890302 , 0.26999833, 0.11194419, 0.17775092],
       [0.8631684 , 0.00894042, 0.8369091

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [185]:

# Author: Bas Swinckels

phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [186]:

# Author: Evgeni Burovski

X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])


[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [187]:

# Author: Jessica B. Hamrick

X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)


[-0.1084268   0.29407967]
